::msgcat::mcset ru "\[J\] Copy %s to clipboard" "\[J\] Скопировать %s в буфер обмена"
::msgcat::mcset ru "\[J\] Open in browser"      "\[J\] Открыть в браузере"
::msgcat::mcset ru "\[J\] Open in new tab"      "\[J\] Открыть в новой вкладке"
::msgcat::mcset ru "\[J\] Subscribe"            "\[J\] Подписаться"
::msgcat::mcset ru "\[J\] Unsubscribe"          "\[J\] Отписаться"

::msgcat::mcset ru "Whether the Juick plugin is loaded." \
"Загружено ли расширение для удобной работы с Juick."

::msgcat::mcset ru "Juick settings." \
"Параметры расширения для удобной работы с Juick."

::msgcat::mcset ru "Main Juick JID. This used for forwarding things from other chats." \
"Главный JID Juick’а. Используется для перенаправления сущностей из других чатов."

::msgcat::mcset ru "Indicate as personal message only private messages and replies to you.\nYour Juick nickname determines at roster receiving, so after enable option you need to reconnecting." \
"Отмечать как персональные только приватные и адресованные вам сообщения.\nВаш псевдоним на Juick определяется при получении ростера, поэтому для работы опции после её включения требуется переподключение."
